Repository Legedith/Dungeons, pull requests merged in 2020-10, with the labels that each got.

#4 Initial commit to remove ascii images from main code and implement OS detection
  ascii_images.py
  dungeons.py
Labels: Hacktoberfest

#6 BUG FIX
  dungeons.py
Labels: Hacktoberfest, bug

#7 Dungeons - find function
  ascii_images.py
  changelog
  dungeons.py
Labels: Hacktoberfest, enhancement
